#!/usr/bin/env python3
"""Regenerates frontend/src/lib/worldMapData.ts from the `@svg-maps/world` package.

    npm pack @svg-maps/world && tar xzf svg-maps-world-*.tgz
    python3 scripts/build_world_map.py package/index.js frontend/src/lib/worldMapData.ts

The source map is ~1.2MB of ultra-detailed relative paths. Every ring is converted
to absolute coordinates, thinned with Ramer-Douglas-Peucker and rounded to one
decimal, which leaves a recognisable world map at a fraction of the size. Map data
(c) Simplemaps / svg-maps contributors, CC BY 4.0 - keep the attribution in the output.
"""

import json
import re
import sys

TOLERANCE = 0.9  # viewBox units (the map is 1010 wide)
MIN_RING_AREA = 0.5  # drops specks; a country's largest ring is always kept
SKIP_IDS_PREFIX = "um-"  # US minor outlying islands: sub-pixel, never an origin country

NUMBER = re.compile(r"-?\d*\.?\d+(?:e-?\d+)?")


def parse_rings(path: str) -> list[list[tuple[float, float]]]:
    """`m x,y dx,dy ... z m dx,dy ...` (relative moveto + implicit relative lineto) -> absolute rings."""
    rings: list[list[tuple[float, float]]] = []
    cx = cy = 0.0
    for chunk in re.split(r"z", path):
        numbers = [float(n) for n in NUMBER.findall(chunk)]
        if len(numbers) < 4:
            continue
        x, y = cx + numbers[0], cy + numbers[1]
        start = (x, y)
        ring = [start]
        for i in range(2, len(numbers) - 1, 2):
            x, y = x + numbers[i], y + numbers[i + 1]
            ring.append((x, y))
        rings.append(ring)
        cx, cy = start  # after `z` the pen returns to the subpath start
    return rings


def perpendicular_distance(p, a, b) -> float:
    (px, py), (ax, ay), (bx, by) = p, a, b
    dx, dy = bx - ax, by - ay
    if dx == dy == 0:
        return ((px - ax) ** 2 + (py - ay) ** 2) ** 0.5
    return abs(dy * px - dx * py + bx * ay - by * ax) / (dx * dx + dy * dy) ** 0.5


def simplify(points: list[tuple[float, float]], tolerance: float) -> list[tuple[float, float]]:
    keep = [False] * len(points)
    keep[0] = keep[-1] = True
    stack = [(0, len(points) - 1)]
    while stack:
        lo, hi = stack.pop()
        far, far_i = 0.0, -1
        for i in range(lo + 1, hi):
            d = perpendicular_distance(points[i], points[lo], points[hi])
            if d > far:
                far, far_i = d, i
        if far > tolerance and far_i != -1:
            keep[far_i] = True
            stack.extend([(lo, far_i), (far_i, hi)])
    return [p for p, k in zip(points, keep, strict=True) if k]


def area(ring) -> float:
    return abs(sum(x1 * y2 - x2 * y1 for (x1, y1), (x2, y2) in zip(ring, ring[1:] + ring[:1], strict=True))) / 2


def fmt(value: float) -> str:
    text = f"{value:.1f}"
    return text[:-2] if text.endswith(".0") else text


def build_path(rings) -> str:
    parts = []
    for ring in rings:
        pts = [(round(x, 1), round(y, 1)) for x, y in ring]
        parts.append("M" + "L".join(f"{fmt(x)} {fmt(y)}" for x, y in pts) + "Z")
    return "".join(parts)


def main(source: str, target: str) -> None:
    raw = open(source, encoding="utf-8").read()
    data = json.loads(raw[raw.index("{"):].rstrip().rstrip(";"))
    countries = []
    for loc in data["locations"]:
        if loc["id"].startswith(SKIP_IDS_PREFIX):
            continue
        rings = parse_rings(loc["path"])
        if not rings:
            continue
        largest = max(rings, key=area)
        kept = []
        for ring in rings:
            if ring is not largest and area(ring) < MIN_RING_AREA:
                continue
            thin = simplify(ring, TOLERANCE)
            kept.append(thin if len(thin) >= 3 else ring[: max(3, len(ring))])
        countries.append({"id": loc["id"].upper(), "name": loc["name"], "d": build_path(kept)})
    countries.sort(key=lambda c: c["id"])

    lines = [
        "// GENERATED by scripts/build_world_map.py - do not edit by hand.",
        "// Map data (c) Simplemaps / svg-maps contributors (@svg-maps/world), CC BY 4.0,",
        "// https://creativecommons.org/licenses/by/4.0/ - simplified for size.",
        "",
        f'export const WORLD_MAP_VIEWBOX = "{data["viewBox"]}";',
        "",
        "export interface MapCountry {",
        "\t/** ISO 3166-1 alpha-2, uppercase - matches the Passport API's country codes. */",
        "\tid: string;",
        "\tname: string;",
        "\td: string;",
        "}",
        "",
        "export const WORLD_MAP: MapCountry[] = [",
    ]
    lines += [f"\t{json.dumps(c, ensure_ascii=False)}," for c in countries]
    lines.append("];")
    with open(target, "w", encoding="utf-8") as out:
        out.write("\n".join(lines) + "\n")
    size = sum(len(c["d"]) for c in countries)
    print(f"{len(countries)} countries, {size / 1024:.0f}KB of path data")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
