"""add run rules_config and step status/watched_at

Revision ID: 0441267a9e2c
Revises: 24c6ae8c0a76
Create Date: 2026-09-12 22:58:35.033007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0441267a9e2c'
down_revision: Union[str, None] = '24c6ae8c0a76'
branch_labels: Union[Sequence[str], None] = None
depends_on: Union[Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default required: SQLite rejects a NOT NULL ADD COLUMN on a
    # non-empty table without one. Existing rows backfill to "watched".
    op.add_column(
        'run_steps',
        sa.Column(
            'status', sqlmodel.sql.sqltypes.AutoString(), nullable=False,
            server_default='watched',
        ),
    )
    op.add_column('run_steps', sa.Column(
        'watched_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_run_steps_status'),
                    'run_steps', ['status'], unique=False)
    op.add_column('runs', sa.Column('rules_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'rules_config')
    op.drop_index(op.f('ix_run_steps_status'), table_name='run_steps')
    op.drop_column('run_steps', 'watched_at')
    op.drop_column('run_steps', 'status')
    # ### end Alembic commands ###
