"""baseline schema

Revision ID: 24c6ae8c0a76
Revises:
Create Date: 2026-09-12 19:44:35.671553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '24c6ae8c0a76'
down_revision: Union[str, None] = None
branch_labels: Union[Sequence[str], None] = None
depends_on: Union[Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cached_actors',
                    sa.Column('tmdb_id', sa.Integer(), nullable=False),
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('profile_path',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('credits_fetched_at',
                              sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('tmdb_id')
                    )
    op.create_table('cached_genres',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('cached_movies',
                    sa.Column('tmdb_id', sa.Integer(), nullable=False),
                    sa.Column(
                        'title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('release_date',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('poster_path', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.Column(
                        'overview', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('origin_country',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('original_language',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('runtime', sa.Integer(), nullable=True),
                    sa.Column('genre_ids', sa.JSON(), nullable=True),
                    sa.Column('cast_fetched_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('tmdb_id')
                    )
    op.create_index(op.f('ix_cached_movies_title'),
                    'cached_movies', ['title'], unique=False)
    op.create_table('runs',
                    sa.Column(
                        'id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('game_type', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column(
                        'status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('completed_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_runs_game_type'), 'runs',
                    ['game_type'], unique=False)
    op.create_index(op.f('ix_runs_status'), 'runs', ['status'], unique=False)
    op.create_table('users',
                    sa.Column(
                        'id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('password_hash',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('is_admin', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_username'),
                    'users', ['username'], unique=True)
    op.create_table('cached_movie_cast',
                    sa.Column('movie_id', sa.Integer(), nullable=False),
                    sa.Column('actor_id', sa.Integer(), nullable=False),
                    sa.Column('cast_order', sa.Integer(), nullable=True),
                    sa.Column('character_name',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['actor_id'], ['cached_actors.tmdb_id'], ),
                    sa.ForeignKeyConstraint(
                        ['movie_id'], ['cached_movies.tmdb_id'], ),
                    sa.PrimaryKeyConstraint('movie_id', 'actor_id')
                    )
    op.create_index(op.f('ix_cached_movie_cast_actor_id'),
                    'cached_movie_cast', ['actor_id'], unique=False)
    op.create_table('run_participants',
                    sa.Column(
                        'run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('joined_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('run_id', 'user_id')
                    )
    op.create_table('run_steps',
                    sa.Column(
                        'id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('movie_id', sa.Integer(), nullable=False),
                    sa.Column('movie_title', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('movie_poster_path',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('movie_release_year',
                              sa.Integer(), nullable=True),
                    sa.Column('movie_origin_country',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('transition_metadata', sa.JSON(), nullable=True),
                    sa.Column('user_notes', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.Column('logged_by_user_id',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('logged_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['logged_by_user_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_run_steps_run_id'),
                    'run_steps', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_run_steps_run_id'), table_name='run_steps')
    op.drop_table('run_steps')
    op.drop_table('run_participants')
    op.drop_index(op.f('ix_cached_movie_cast_actor_id'),
                  table_name='cached_movie_cast')
    op.drop_table('cached_movie_cast')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_runs_status'), table_name='runs')
    op.drop_index(op.f('ix_runs_game_type'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_cached_movies_title'), table_name='cached_movies')
    op.drop_table('cached_movies')
    op.drop_table('cached_genres')
    op.drop_table('cached_actors')
    # ### end Alembic commands ###
