"""add cached_movie_ratings table

Revision ID: a1b2c3d4e5f6
Revises: f793f6193ddb
Create Date: 2026-09-13 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = 'f793f6193ddb'
branch_labels: Union[Sequence[str], None] = None
depends_on: Union[Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cached_movie_ratings',
                    sa.Column('movie_id', sa.Integer(), nullable=False),
                    sa.Column(
                        'imdb_rating', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('rotten_tomatoes',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('metacritic', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.Column('fetched_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['movie_id'], ['cached_movies.tmdb_id'], ),
                    sa.PrimaryKeyConstraint('movie_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cached_movie_ratings')
    # ### end Alembic commands ###
