"""add curated canon & letterboxd watchlist tables

Revision ID: c3d4e5f6a7b8
Revises: b2c3d4e5f6a7
Create Date: 2026-10-03 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c3d4e5f6a7b8'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[Sequence[str], None] = None
depends_on: Union[Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curated_source_accounts',
                    sa.Column(
                        'id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('display_name',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_curated_source_accounts_username'),
                    'curated_source_accounts', ['username'], unique=True)
    op.create_table('curated_lists',
                    sa.Column(
                        'id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'preset_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('source_account_id',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('badge_prefix', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('badge_color', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('is_ranked', sa.Boolean(), nullable=False),
                    sa.Column('total_items', sa.Integer(), nullable=False),
                    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
                    sa.Column('last_sync_error',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['source_account_id'], [
                        'curated_source_accounts.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_curated_lists_preset_key'),
                    'curated_lists', ['preset_key'], unique=False)
    op.create_table('canon_movie_badges',
                    sa.Column(
                        'id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'curated_list_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('movie_id', sa.Integer(), nullable=False),
                    sa.Column('badge_label', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('rank', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['curated_list_id'], [
                                            'curated_lists.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_canon_movie_badges_curated_list_id'),
                    'canon_movie_badges', ['curated_list_id'], unique=False)
    op.create_index(op.f('ix_canon_movie_badges_movie_id'),
                    'canon_movie_badges', ['movie_id'], unique=False)
    op.create_table('letterboxd_watchlists',
                    sa.Column(
                        'id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('letterboxd_username',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('movie_id', sa.Integer(), nullable=False),
                    sa.Column(
                        'title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('year', sa.Integer(), nullable=True),
                    sa.Column('synced_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_letterboxd_watchlists_user_id'),
                    'letterboxd_watchlists', ['user_id'], unique=False)
    op.create_index(op.f('ix_letterboxd_watchlists_movie_id'),
                    'letterboxd_watchlists', ['movie_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_letterboxd_watchlists_movie_id'),
                  table_name='letterboxd_watchlists')
    op.drop_index(op.f('ix_letterboxd_watchlists_user_id'),
                  table_name='letterboxd_watchlists')
    op.drop_table('letterboxd_watchlists')
    op.drop_index(op.f('ix_canon_movie_badges_movie_id'),
                  table_name='canon_movie_badges')
    op.drop_index(op.f('ix_canon_movie_badges_curated_list_id'),
                  table_name='canon_movie_badges')
    op.drop_table('canon_movie_badges')
    op.drop_index(op.f('ix_curated_lists_preset_key'),
                  table_name='curated_lists')
    op.drop_table('curated_lists')
    op.drop_index(op.f('ix_curated_source_accounts_username'),
                  table_name='curated_source_accounts')
    op.drop_table('curated_source_accounts')
    # ### end Alembic commands ###
