"""add popularity to cached_movies

Revision ID: f793f6193ddb
Revises: e84e72f303ff
Create Date: 2026-09-13 16:44:35.761260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f793f6193ddb'
down_revision: Union[str, None] = 'e84e72f303ff'
branch_labels: Union[Sequence[str], None] = None
depends_on: Union[Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cached_movies', sa.Column('popularity', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cached_movies', 'popularity')
    # ### end Alembic commands ###
